module

public import Mathlib.Algebra.Polynomial.Derivative
public import Mathlib.Algebra.Polynomial.Roots
public import Mathlib.RingTheory.Adjoin.Basic
public import Mathlib.RingTheory.MvPolynomial.WeightedHomogeneous
public import Mathlib.Algebra.MvPolynomial.PDeriv
public import Mathlib.Algebra.BigOperators.Finprod
public import Mathlib.Data.Complex.Basic

@[expose] public section

/-!
# Six homogeneous components in the first Weyl algebra

The algebra is realized by multiplication and differentiation on K[X]. In
characteristic zero this is the faithful first Weyl algebra representation.
The displayed coefficient inversion formula defines the PBW symbol, and mass
counts its occupied grades i-j. One grade may contain arbitrarily many monomials.
The theorem asserts generation over every characteristic-zero field, with no
bound on the degree, order, support or mass of Q.
-/

namespace Dixmier.Weyl

open Polynomial

section Operators

variable (K : Type*) [Field K]

/-- Multiplication by the variable `X`, as a linear operator on `K[X]`. -/
noncomputable def xOp : Module.End K K[X] := LinearMap.mulLeft K (X : K[X])

/-- Differentiation, as a linear operator on `K[X]`. -/
noncomputable def yOp : Module.End K K[X] := Polynomial.derivative

/-- The first Weyl algebra `A₁(K)`, realized as the subalgebra of `End_K(K[X])` generated by
`xOp` and `yOp`. -/
noncomputable def A1 : Subalgebra K (Module.End K K[X]) := Algebra.adjoin K {xOp K, yOp K}

end Operators

section Symbols

variable {K : Type*} [Field K]

/-- The `j`-th coefficient polynomial `a_j` of an operator `T = ∑_j a_j(X) ∂^j`. -/
noncomputable def coeffPoly (T : Module.End K K[X]) (j : ℕ) : K[X] :=
  C ((j.factorial : K)⁻¹) * ∑ k ∈ Finset.range (j + 1),
    C ((-1) ^ (j - k) * (j.choose k : K)) * X ^ (j - k) * T (X ^ k)

/-- The PBW coefficient of `X^i Y^j`. -/
noncomputable def pbwCoeff (T : Module.End K K[X]) (i j : ℕ) : K := (coeffPoly T j).coeff i

/-- The exponent `x^i y^j` in `K[x, y] = MvPolynomial (Fin 2) K`. -/
noncomputable def expo (i j : ℕ) : Fin 2 →₀ ℕ := Finsupp.single 0 i + Finsupp.single 1 j

/-- The PBW symbol `ψ(T) = ∑ p_{ij} x^i y^j`. -/
noncomputable def symbol (T : Module.End K K[X]) : MvPolynomial (Fin 2) K :=
  ∑ᶠ p : ℕ × ℕ, MvPolynomial.monomial (expo p.1 p.2) (pbwCoeff T p.1 p.2)

/-- The grade `i - j` of the exponent `x^i y^j`. -/
def grade (d : Fin 2 →₀ ℕ) : ℤ := (d 0 : ℤ) - d 1

/-- The mass: the number of distinct grades in the PBW support. -/
noncomputable def mass (T : Module.End K K[X]) : ℕ := ((symbol T).support.image grade).card

end Symbols
end Dixmier.Weyl

namespace Dixmier.Palomar

/-- If P and Q belong to the first Weyl algebra over any characteristic-zero
field, QP-PQ=1, and P has at most six nonzero homogeneous components for the
X-degree one, Y-degree minus one grading, then P and Q generate the algebra.
The mate Q has no degree, order or mass restriction. -/
theorem massSixGeneration.{u}
    (K : Type u) [Field K] [CharZero K] (P Q : Dixmier.Weyl.A1 K)
    (hcomm : Q * P - P * Q = 1) (hmass : Dixmier.Weyl.mass P.1 ≤ 6) :
    Algebra.adjoin K {P, Q} = ⊤ := by
  sorry

end Dixmier.Palomar
