/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module

public import DixmierFormal.Weyl.Validation
public import Mathlib.Algebra.FreeAlgebra
public import Mathlib.RingTheory.Ideal.Quotient.Basic
public import Mathlib.RingTheory.Ideal.Quotient.Operations

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

/-!
# Abstract rank-one Weyl presentation: quotient map to the operator model

The free algebra uses generators `0 = X` and `1 = Y`. We quotient by the two-sided ideal
containing all two-sided multiples of `YX - XY - 1`, matching the convention `[Y, X] = 1`.
This module constructs the canonical map to the polynomial differential-operator model and proves
it is surjective in all characteristics. In characteristic zero, a quotient PBW normal form and
concrete coefficient extraction prove that the map is injective as well.
-/

namespace Dixmier.Weyl

open Polynomial

noncomputable section

variable (K : Type*) [Field K]

/-- The free associative `K`-algebra on the two Weyl generators. -/
abbrev WeylFreeAlgebra := FreeAlgebra K (Fin 2)

/-- The defining relation `YX - XY - 1`. -/
def weylRelation : WeylFreeAlgebra K :=
  FreeAlgebra.ι K 1 * FreeAlgebra.ι K 0 -
    FreeAlgebra.ι K 0 * FreeAlgebra.ι K 1 - algebraMap K (WeylFreeAlgebra K) 1

/-- All two-sided multiples of the Weyl relation. -/
def weylRelationMultiples : Set (WeylFreeAlgebra K) :=
  Set.range fun p : WeylFreeAlgebra K × WeylFreeAlgebra K =>
    p.1 * weylRelation K * p.2

/-- The left ideal generated by every two-sided multiple of the relation. -/
def weylRelationIdeal : Ideal (WeylFreeAlgebra K) :=
  Ideal.span (weylRelationMultiples K)

/-- The relation ideal is two-sided: right multiplication just changes the right factor. -/
instance weylRelationIdeal_isTwoSided : (weylRelationIdeal K).IsTwoSided where
  mul_mem_of_left b ha := by
    let J : Ideal (WeylFreeAlgebra K) := {
      carrier := {x | x * b ∈ weylRelationIdeal K}
      add_mem' := by
        intro x y hx hy
        change (x + y) * b ∈ weylRelationIdeal K
        rw [add_mul]
        exact (weylRelationIdeal K).add_mem hx hy
      zero_mem' := by simp
      smul_mem' := by
        intro c x hx
        change (c * x) * b ∈ weylRelationIdeal K
        rw [mul_assoc]
        exact (weylRelationIdeal K).mul_mem_left c hx
    }
    have hsub : weylRelationMultiples K ⊆ (J : Set (WeylFreeAlgebra K)) := by
      rintro x ⟨⟨u, v⟩, rfl⟩
      change (u * weylRelation K * v) * b ∈ weylRelationIdeal K
      apply Ideal.subset_span
      refine ⟨(u, v * b), ?_⟩
      simp [mul_assoc]
    exact (Ideal.span_le.2 hsub) ha

/-- The abstract Weyl algebra as the free algebra modulo the two-sided Weyl relation. -/
abbrev AbstractA1 := (WeylFreeAlgebra K) ⧸ weylRelationIdeal K

/-- The class of the free `X` generator in the abstract quotient. -/
def abstractX : AbstractA1 K :=
  Ideal.Quotient.mkₐ K (weylRelationIdeal K) (FreeAlgebra.ι K 0)

/-- The class of the free `Y` generator in the abstract quotient. -/
def abstractY : AbstractA1 K :=
  Ideal.Quotient.mkₐ K (weylRelationIdeal K) (FreeAlgebra.ι K 1)

/-- The quotient generators satisfy exactly the Weyl relation. -/
theorem abstract_relation :
    abstractY K * abstractX K - abstractX K * abstractY K - 1 = 0 := by
  have hmem : weylRelation K ∈ weylRelationIdeal K := by
    apply Ideal.subset_span
    exact ⟨(1, 1), by simp⟩
  have hzero : Ideal.Quotient.mk (weylRelationIdeal K) (weylRelation K) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr hmem
  calc
    abstractY K * abstractX K - abstractX K * abstractY K - 1 =
        Ideal.Quotient.mk (weylRelationIdeal K) (weylRelation K) := by
      simp [abstractX, abstractY, weylRelation, Ideal.Quotient.mkₐ_eq_mk]
    _ = 0 := hzero

/-- The multiplication-by-`X` generator inside the concrete operator algebra. -/
def concreteX : A1 K := ⟨xOp K, by
  change xOp K ∈ Algebra.adjoin K {xOp K, yOp K}
  exact Algebra.subset_adjoin (by simp)⟩

/-- The differentiation generator inside the concrete operator algebra. -/
def concreteY : A1 K := ⟨yOp K, by
  change yOp K ∈ Algebra.adjoin K {xOp K, yOp K}
  exact Algebra.subset_adjoin (by simp)⟩

/-- Images of the two free generators, with indices `0 = X` and `1 = Y`. -/
def abstractGenerators : Fin 2 → A1 K := fun i =>
  if i = 0 then concreteX K else concreteY K

@[simp]
theorem abstractGenerators_zero : abstractGenerators K 0 = concreteX K := by
  simp [abstractGenerators]

@[simp]
theorem abstractGenerators_one : abstractGenerators K 1 = concreteY K := by
  simp [abstractGenerators]

/-- The free-algebra map sending `X` to multiplication and `Y` to differentiation. -/
def evaluateWeylFree : WeylFreeAlgebra K →ₐ[K] A1 K :=
  FreeAlgebra.lift K (abstractGenerators K)

/-- The operator model satisfies the defining relation. -/
theorem evaluateWeylFree_relation : evaluateWeylFree K (weylRelation K) = 0 := by
  have h : yOp K * xOp K - xOp K * yOp K - 1 = 0 := by
    rw [yOp_mul_xOp_sub_xOp_mul_yOp]
    simp
  apply Subtype.ext
  simp only [evaluateWeylFree, weylRelation, map_sub, map_mul, map_one,
    FreeAlgebra.lift_ι_apply, abstractGenerators_zero, abstractGenerators_one]
  simpa [concreteX, concreteY] using h

/-- The evaluation map kills the whole two-sided ideal generated by the relation. -/
theorem evaluateWeylFree_zero_on_relationIdeal
    (a : WeylFreeAlgebra K) (ha : a ∈ weylRelationIdeal K) : evaluateWeylFree K a = 0 := by
  unfold weylRelationIdeal at ha
  change a ∈ Submodule.span (WeylFreeAlgebra K) (weylRelationMultiples K) at ha
  refine Submodule.span_induction (R := WeylFreeAlgebra K) (s := weylRelationMultiples K)
    (p := fun x _ => evaluateWeylFree K x = 0) ?_ ?_ ?_ ?_ ha
  · intro x hx
    rcases hx with ⟨⟨u, v⟩, rfl⟩
    simp only [map_mul]
    rw [evaluateWeylFree_relation]
    simp
  · simp
  · intro x y hx hy hxe hye
    simp [map_add, hxe, hye]
  · intro c x hx hxe
    change evaluateWeylFree K (c * x) = 0
    rw [map_mul, hxe]
    simp

/-- The canonical homomorphism from the abstract presentation to polynomial differential
operators. -/
def abstractToConcrete : AbstractA1 K →ₐ[K] A1 K :=
  Ideal.Quotient.liftₐ (weylRelationIdeal K) (evaluateWeylFree K)
    (evaluateWeylFree_zero_on_relationIdeal K)

@[simp]
theorem abstractToConcrete_mk (a : WeylFreeAlgebra K) :
    abstractToConcrete K (Ideal.Quotient.mkₐ K (weylRelationIdeal K) a) =
      evaluateWeylFree K a := by
  change ((Ideal.Quotient.liftₐ (weylRelationIdeal K) (evaluateWeylFree K)
    (evaluateWeylFree_zero_on_relationIdeal K)).comp
      (Ideal.Quotient.mkₐ K (weylRelationIdeal K))) a = evaluateWeylFree K a
  rw [Ideal.Quotient.liftₐ_comp]

/-- The abstract presentation maps onto the concrete operator algebra. -/
theorem abstractToConcrete_surjective : Function.Surjective (abstractToConcrete K) := by
  intro z
  have hgen : ∀ (x : Module.End K K[X]) (hx : x ∈ Algebra.adjoin K {xOp K, yOp K}),
      ∃ a : AbstractA1 K, abstractToConcrete K a = (⟨x, hx⟩ : A1 K) := by
    intro x hx
    induction hx using Algebra.adjoin_induction with
    | mem x hx =>
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
        rcases hx with hx | hx
        · subst x
          refine ⟨abstractX K, ?_⟩
          apply Subtype.ext
          rw [abstractX, abstractToConcrete_mk]
          simp [evaluateWeylFree, FreeAlgebra.lift_ι_apply, abstractGenerators_zero, concreteX]
        · subst x
          refine ⟨abstractY K, ?_⟩
          apply Subtype.ext
          rw [abstractY, abstractToConcrete_mk]
          simp [evaluateWeylFree, FreeAlgebra.lift_ι_apply, abstractGenerators_one, concreteY]
    | algebraMap c =>
        refine ⟨algebraMap K (AbstractA1 K) c, ?_⟩
        apply Subtype.ext
        simp [abstractToConcrete]
    | add x y hx hy ihx ihy =>
        rcases ihx with ⟨a, ha⟩
        rcases ihy with ⟨b, hb⟩
        refine ⟨a + b, ?_⟩
        apply Subtype.ext
        simp only [map_add]
        exact congrArg₂ (· + ·) (congrArg Subtype.val ha) (congrArg Subtype.val hb)
    | mul x y hx hy ihx ihy =>
        rcases ihx with ⟨a, ha⟩
        rcases ihy with ⟨b, hb⟩
        refine ⟨a * b, ?_⟩
        apply Subtype.ext
        simp only [map_mul]
        exact congrArg₂ (· * ·) (congrArg Subtype.val ha) (congrArg Subtype.val hb)
  exact hgen z z.property

/-- The quotient relation in the convenient `YX = XY + 1` form. -/
theorem abstract_y_mul_x : abstractY K * abstractX K = abstractX K * abstractY K + 1 := by
  have h := abstract_relation K
  have h' := congrArg (fun z : AbstractA1 K => z + (abstractX K * abstractY K + 1)) h
  simpa [sub_eq_add_neg, add_assoc, add_comm, add_left_comm] using h'

/-- Commuting a positive power of `Y` past one `X` uses only the defining relation. -/
theorem abstract_y_pow_succ_mul_x (n : ℕ) :
    abstractY K ^ (n + 1) * abstractX K =
      abstractX K * abstractY K ^ (n + 1) + (n + 1 : K) • abstractY K ^ n := by
  induction n with
  | zero =>
      simpa using abstract_y_mul_x K
  | succ n ih =>
      simp only [Nat.cast_add, Nat.cast_one]
      calc
        abstractY K ^ (n + 1 + 1) * abstractX K =
            (abstractY K ^ (n + 1) * abstractY K) * abstractX K := by rw [pow_succ]
        _ = abstractY K ^ (n + 1) * (abstractY K * abstractX K) := by simp [mul_assoc]
        _ = abstractY K ^ (n + 1) * (abstractX K * abstractY K + 1) := by rw [abstract_y_mul_x]
        _ = (abstractY K ^ (n + 1) * abstractX K) * abstractY K + abstractY K ^ (n + 1) := by
              simp [mul_add, mul_one, mul_assoc]
        _ = (abstractX K * abstractY K ^ (n + 1) + (n + 1 : K) • abstractY K ^ n) * abstractY K +
              abstractY K ^ (n + 1) := by rw [ih]
        _ = abstractX K * abstractY K ^ (n + 1 + 1) + ((n + 1 : K) + 1) • abstractY K ^ (n + 1) := by
              rw [add_mul]
              have hcoeff : (n + 1 : K) • abstractY K ^ (n + 1) + abstractY K ^ (n + 1) =
                  ((n + 1 : K) + 1) • abstractY K ^ (n + 1) := by
                calc
                  _ = (n + 1 : K) • abstractY K ^ (n + 1) + (1 : K) • abstractY K ^ (n + 1) := by simp
                  _ = ((n + 1 : K) + 1) • abstractY K ^ (n + 1) := by rw [← add_smul]
              have hp1 : abstractY K ^ (n + 1) * abstractY K = abstractY K ^ (n + 1 + 1) := by
                simpa [Nat.add_assoc] using (pow_succ (abstractY K) (n + 1)).symm
              have hp0 : abstractY K ^ n * abstractY K = abstractY K ^ (n + 1) := by
                rw [pow_succ]
              calc
                abstractX K * abstractY K ^ (n + 1) * abstractY K +
                    ((n + 1 : K) • abstractY K ^ n) * abstractY K + abstractY K ^ (n + 1) =
                    abstractX K * abstractY K ^ (n + 1 + 1) +
                      (n + 1 : K) • abstractY K ^ (n + 1) + abstractY K ^ (n + 1) := by
                        rw [mul_assoc, hp1, smul_mul_assoc, hp0]
                _ = abstractX K * abstractY K ^ (n + 1 + 1) +
                      ((n + 1 : K) + 1) • abstractY K ^ (n + 1) := by
                        rw [add_assoc, hcoeff]
                _ = abstractX K * abstractY K ^ (n + 1 + 1) +
                      (n + 1 + 1 : K) • abstractY K ^ (n + 1) := by
                        congr 1

/-- An ordered monomial in the abstract quotient. -/
noncomputable def abstractNormalMonomial (i j : ℕ) : AbstractA1 K :=
  abstractX K ^ i * abstractY K ^ j

/-- The K-linear span of ordered monomials in the abstract quotient. -/
noncomputable def abstractNormalSpan : Submodule K (AbstractA1 K) :=
  Submodule.span K (Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2)

theorem abstractNormalMonomial_mem (i j : ℕ) :
    abstractNormalMonomial K i j ∈ abstractNormalSpan K := by
  apply Submodule.subset_span
  exact ⟨(i,j), rfl⟩

theorem abstractNormalMonomial_mul_x_mem (i j : ℕ) :
    abstractNormalMonomial K i j * abstractX K ∈ abstractNormalSpan K := by
  cases j with
  | zero =>
      apply Submodule.subset_span
      refine ⟨(i+1,0), ?_⟩
      dsimp [abstractNormalMonomial]
      simp only [pow_zero, mul_one]
      rw [pow_succ]
  | succ j =>
      have hEq : abstractNormalMonomial K i (j+1) * abstractX K =
          abstractNormalMonomial K (i+1) (j+1) +
            (j+1 : K) • abstractNormalMonomial K i j := by
        dsimp [abstractNormalMonomial]
        calc
          abstractX K ^ i * abstractY K ^ (j+1) * abstractX K =
              abstractX K ^ i * (abstractY K ^ (j+1) * abstractX K) := by rw [mul_assoc]
          _ = abstractX K ^ i *
                (abstractX K * abstractY K ^ (j+1) + (j+1 : K) • abstractY K ^ j) := by
                rw [abstract_y_pow_succ_mul_x]
          _ = (abstractX K ^ i * abstractX K) * abstractY K ^ (j+1) +
                (j+1 : K) • (abstractX K ^ i * abstractY K ^ j) := by
                rw [mul_add, mul_smul_comm, mul_assoc]
          _ = abstractX K ^ (i+1) * abstractY K ^ (j+1) +
                (j+1 : K) • (abstractX K ^ i * abstractY K ^ j) := by
                rw [← pow_succ]
      rw [hEq]
      exact Submodule.add_mem _ (abstractNormalMonomial_mem K (i+1) (j+1))
        (Submodule.smul_mem _ _ (abstractNormalMonomial_mem K i j))

private theorem abstractNormalSpan_mul_x {z : AbstractA1 K}
    (hz : z ∈ abstractNormalSpan K) : z * abstractX K ∈ abstractNormalSpan K := by
  unfold abstractNormalSpan at hz ⊢
  refine Submodule.span_induction (R := K)
    (s := Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2)
    (p := fun z _ => z * abstractX K ∈
      Submodule.span K (Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2))
    ?_ ?_ ?_ ?_ hz
  · intro z hz
    rcases hz with ⟨p, rfl⟩
    exact abstractNormalMonomial_mul_x_mem K p.1 p.2
  · simp
  · intro x y hx hy hxe hye
    change (x + y) * abstractX K ∈ _
    rw [add_mul]
    exact (Submodule.span K (Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2)).add_mem hxe hye
  · intro c x hx hxe
    change (c • x) * abstractX K ∈ _
    rw [smul_mul_assoc]
    exact Submodule.smul_mem _ _ hxe

theorem abstractNormalMonomial_mul_y_mem (i j : ℕ) :
    abstractNormalMonomial K i j * abstractY K ∈ abstractNormalSpan K := by
  change abstractX K ^ i * abstractY K ^ j * abstractY K ∈ abstractNormalSpan K
  rw [mul_assoc, ← pow_succ]
  exact abstractNormalMonomial_mem K i (j + 1)

private theorem abstractNormalSpan_mul_y {z : AbstractA1 K}
    (hz : z ∈ abstractNormalSpan K) : z * abstractY K ∈ abstractNormalSpan K := by
  unfold abstractNormalSpan at hz ⊢
  refine Submodule.span_induction (R := K)
    (s := Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2)
    (p := fun z _ => z * abstractY K ∈
      Submodule.span K (Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2))
    ?_ ?_ ?_ ?_ hz
  · intro z hz
    rcases hz with ⟨p, rfl⟩
    exact abstractNormalMonomial_mul_y_mem K p.1 p.2
  · simp
  · intro x y hx hy hxe hye
    change (x + y) * abstractY K ∈ _
    rw [add_mul]
    exact (Submodule.span K (Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2)).add_mem hxe hye
  · intro c x hx hxe
    change (c • x) * abstractY K ∈ _
    rw [smul_mul_assoc]
    exact Submodule.smul_mem _ _ hxe

private theorem abstractNormalSpan_mul_normalMonomial {z : AbstractA1 K}
    (hz : z ∈ abstractNormalSpan K) (i j : ℕ) :
    z * abstractNormalMonomial K i j ∈ abstractNormalSpan K := by
  have hx : ∀ n : ℕ, z * abstractX K ^ n ∈ abstractNormalSpan K := by
    intro n
    induction n with
    | zero => simpa using hz
    | succ n hn =>
        rw [pow_succ, ← mul_assoc]
        exact abstractNormalSpan_mul_x K hn
  have hy : ∀ n : ℕ, z * abstractX K ^ i * abstractY K ^ n ∈ abstractNormalSpan K := by
    intro n
    induction n with
    | zero => simpa using hx i
    | succ n hn =>
        rw [pow_succ, ← mul_assoc]
        exact abstractNormalSpan_mul_y K hn
  simpa [abstractNormalMonomial, mul_assoc] using hy j

private theorem abstractNormalSpan_mul {z w : AbstractA1 K}
    (hz : z ∈ abstractNormalSpan K) (hw : w ∈ abstractNormalSpan K) :
    z * w ∈ abstractNormalSpan K := by
  unfold abstractNormalSpan at hw ⊢
  refine Submodule.span_induction (R := K)
    (s := Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2)
    (p := fun w _ => z * w ∈
      Submodule.span K (Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2))
    ?_ ?_ ?_ ?_ hw
  · intro w hw
    rcases hw with ⟨p, rfl⟩
    exact abstractNormalSpan_mul_normalMonomial K hz p.1 p.2
  · simp
  · intro a b ha hb hae hbe
    change z * (a + b) ∈ _
    rw [mul_add]
    exact (Submodule.span K (Set.range fun p : ℕ × ℕ => abstractNormalMonomial K p.1 p.2)).add_mem hae hbe
  · intro c w hw hwe
    change z * (c • w) ∈ _
    rw [mul_smul_comm]
    exact Submodule.smul_mem _ _ hwe

private theorem one_mem_abstractNormalSpan : (1 : AbstractA1 K) ∈ abstractNormalSpan K := by
  simpa [abstractNormalMonomial] using abstractNormalMonomial_mem K 0 0

private theorem abstractX_mem_abstractNormalSpan : abstractX K ∈ abstractNormalSpan K := by
  simpa [abstractNormalMonomial] using abstractNormalMonomial_mem K 1 0

private theorem abstractY_mem_abstractNormalSpan : abstractY K ∈ abstractNormalSpan K := by
  simpa [abstractNormalMonomial] using abstractNormalMonomial_mem K 0 1

/-- Evaluate free words at the quotient generators. -/
def abstractEvaluateFree : WeylFreeAlgebra K →ₐ[K] AbstractA1 K :=
  Ideal.Quotient.mkₐ K (weylRelationIdeal K)

private theorem abstractEvaluateFree_mem (a : WeylFreeAlgebra K) :
    abstractEvaluateFree K a ∈ abstractNormalSpan K := by
  induction a using FreeAlgebra.induction with
  | grade0 c =>
      change algebraMap K (AbstractA1 K) c ∈ abstractNormalSpan K
      rw [Algebra.algebraMap_eq_smul_one]
      exact Submodule.smul_mem _ c (one_mem_abstractNormalSpan K)
  | grade1 i =>
      fin_cases i
      · simpa [abstractEvaluateFree, abstractX] using abstractX_mem_abstractNormalSpan K
      · simpa [abstractEvaluateFree, abstractY] using abstractY_mem_abstractNormalSpan K
  | mul a b ha hb =>
      simpa [abstractEvaluateFree] using abstractNormalSpan_mul K ha hb
  | add a b ha hb =>
      simpa [abstractEvaluateFree] using
        (Submodule.add_mem (abstractNormalSpan K) ha hb)

/-- Every class in the abstract Weyl presentation is a finite linear combination of ordered
monomials `X^i Y^j`. -/
theorem abstractNormalSpan_eq_top : abstractNormalSpan K = ⊤ := by
  apply top_unique
  intro z hz
  rcases Ideal.Quotient.mk_surjective z with ⟨a, rfl⟩
  simpa [abstractEvaluateFree, Ideal.Quotient.mkₐ_eq_mk] using abstractEvaluateFree_mem K a

@[simp]
theorem abstractToConcrete_abstractX : abstractToConcrete K (abstractX K) = concreteX K := by
  apply Subtype.ext
  rw [abstractX, abstractToConcrete_mk]
  simp [evaluateWeylFree, abstractGenerators_zero, concreteX]

@[simp]
theorem abstractToConcrete_abstractY : abstractToConcrete K (abstractY K) = concreteY K := by
  apply Subtype.ext
  rw [abstractY, abstractToConcrete_mk]
  simp [evaluateWeylFree, abstractGenerators_one, concreteY]

@[simp]
theorem abstractToConcrete_normalMonomial (i j : ℕ) :
    abstractToConcrete K (abstractNormalMonomial K i j) =
      concreteX K ^ i * concreteY K ^ j := by
  simp [abstractNormalMonomial]

/-- A finite normal-ordered sum in the abstract quotient. -/
noncomputable def abstractNormalOrderedSum (c : (ℕ × ℕ) →₀ K) : AbstractA1 K :=
  c.sum (fun p a => a • abstractNormalMonomial K p.1 p.2)

/-- Every element has a finite ordered-monomial expansion in the abstract quotient. -/
theorem abstract_exists_finiteNormalOrderedExpansion (z : AbstractA1 K) :
    ∃ c : (ℕ × ℕ) →₀ K, abstractNormalOrderedSum K c = z := by
  have hmem : z ∈ abstractNormalSpan K := by
    rw [abstractNormalSpan_eq_top K]
    exact Submodule.mem_top
  obtain ⟨c, hc⟩ := Finsupp.mem_span_range_iff_exists_finsupp.mp hmem
  exact ⟨c, hc⟩

theorem abstractToConcrete_normalOrderedSum_val (c : (ℕ × ℕ) →₀ K) :
    ((abstractToConcrete K (abstractNormalOrderedSum K c) : A1 K) : Module.End K K[X]) =
      c.sum (fun p a => a • normalOrderedMonomial (K := K) p.1 p.2) := by
  classical
  simp [abstractNormalOrderedSum, abstractNormalMonomial, normalOrderedMonomial,
    concreteX, concreteY, Finsupp.sum]

section Injectivity

variable [CharZero K]

private theorem abstractToConcrete_zero_imp_zero {z : AbstractA1 K}
    (hz : abstractToConcrete K z = 0) : z = 0 := by
  obtain ⟨c, hc⟩ := abstract_exists_finiteNormalOrderedExpansion K z
  have hmap : abstractToConcrete K (abstractNormalOrderedSum K c) = 0 := by
    rw [hc]
    exact hz
  have hval : c.sum (fun p a => a • normalOrderedMonomial (K := K) p.1 p.2) = 0 := by
    have h := congrArg Subtype.val hmap
    rw [abstractToConcrete_normalOrderedSum_val] at h
    exact h
  have hcoeff : ∀ p : ℕ × ℕ, c p = 0 := by
    intro p
    have h := congrArg (fun T => pbwCoeff T p.1 p.2) hval
    rw [pbwCoeff_finsuppNormalOrderedSum] at h
    simpa [pbwCoeff, coeffPoly] using h
  have hc0 : c = 0 := by
    ext p
    exact hcoeff p
  rw [← hc, abstractNormalOrderedSum, hc0]
  simp

/-- The canonical abstract Weyl presentation embeds into the concrete operator model in
characteristic zero; its proof is the PBW normal-form argument. -/
theorem abstractToConcrete_injective : Function.Injective (abstractToConcrete K) := by
  intro a b hab
  have hzero : a - b = 0 := by
    apply abstractToConcrete_zero_imp_zero K
    rw [map_sub, hab, sub_self]
  exact sub_eq_zero.mp hzero

/-- The abstract two-generator quotient is canonically isomorphic to the concrete differential
operator model over a characteristic-zero field. -/
noncomputable def abstractToConcreteEquiv : AbstractA1 K ≃ₐ[K] A1 K :=
  AlgEquiv.ofBijective (abstractToConcrete K)
    ⟨abstractToConcrete_injective K, abstractToConcrete_surjective K⟩

end Injectivity

end

end Dixmier.Weyl
