/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module

public import Mathlib.Algebra.Polynomial.Derivative
public import Mathlib.Algebra.Polynomial.Roots
public import Mathlib.RingTheory.Adjoin.Basic
public import Mathlib.RingTheory.MvPolynomial.WeightedHomogeneous
public import Mathlib.Algebra.MvPolynomial.PDeriv
public import Mathlib.Algebra.BigOperators.Finprod
public import Mathlib.Data.Complex.Basic

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

/-!
# The first Weyl algebra and its Newton data (frozen contract)

* `A1 K`: the subalgebra of `End_K(K[X])` generated by multiplication by `X` (`xOp`) and
  differentiation (`yOp`).  It satisfies `[yOp, xOp] = 1`, the paper's convention `[Y, X] = 1`.
* `pbwCoeff T i j`: the coefficient of `X^i Y^j` (powers of `X` on the left) of an operator,
  read off by the inversion formula
  `a_j = (1/j!) ∑_{k ≤ j} (-1)^{j-k} C(j,k) X^{j-k} T(X^k)` for `T = ∑_j a_j(X) ∂^j`.
  It is defined for every linear operator; on `A1 K` it is the PBW coefficient.
* `symbol T ∈ K[x, y]` (`x = X 0`, `y = X 1`): the PBW symbol `ψ(T) = ∑ p_{ij} x^i y^j`.
* `mass`, weighted degree `vDeg`, leading form `leadingForm`, directions, strict crossings,
  the Poisson bracket, the Fourier exchange and the cut polynomial.

No definition here depends on a proof.  Facts such as finiteness of PBW supports on `A1 K`
are theorems, not definitional inputs.  This module is part of the frozen statement contract.
-/

namespace Dixmier.Weyl

open Polynomial

section Operators

variable (K : Type*) [Field K]

/-- Multiplication by the variable `X`, as a linear operator on `K[X]`. -/
noncomputable def xOp : Module.End K K[X] := LinearMap.mulLeft K (X : K[X])

/-- Differentiation, as a linear operator on `K[X]`. -/
noncomputable def yOp : Module.End K K[X] := Polynomial.derivative

/-- The first Weyl algebra `A₁(K)`, realized as the subalgebra of `End_K(K[X])` generated by
`xOp` and `yOp`. -/
noncomputable def A1 : Subalgebra K (Module.End K K[X]) := Algebra.adjoin K {xOp K, yOp K}

end Operators

section Symbols

variable {K : Type*} [Field K]

/-- The `j`-th coefficient polynomial `a_j` of an operator `T = ∑_j a_j(X) ∂^j`. -/
noncomputable def coeffPoly (T : Module.End K K[X]) (j : ℕ) : K[X] :=
  C ((j.factorial : K)⁻¹) * ∑ k ∈ Finset.range (j + 1),
    C ((-1) ^ (j - k) * (j.choose k : K)) * X ^ (j - k) * T (X ^ k)

/-- The PBW coefficient of `X^i Y^j`. -/
noncomputable def pbwCoeff (T : Module.End K K[X]) (i j : ℕ) : K := (coeffPoly T j).coeff i

/-- The exponent `x^i y^j` in `K[x, y] = MvPolynomial (Fin 2) K`. -/
noncomputable def expo (i j : ℕ) : Fin 2 →₀ ℕ := Finsupp.single 0 i + Finsupp.single 1 j

/-- The PBW symbol `ψ(T) = ∑ p_{ij} x^i y^j`. -/
noncomputable def symbol (T : Module.End K K[X]) : MvPolynomial (Fin 2) K :=
  ∑ᶠ p : ℕ × ℕ, MvPolynomial.monomial (expo p.1 p.2) (pbwCoeff T p.1 p.2)

/-- The grade `i - j` of the exponent `x^i y^j`. -/
def grade (d : Fin 2 →₀ ℕ) : ℤ := (d 0 : ℤ) - d 1

/-- The mass: the number of distinct grades in the PBW support. -/
noncomputable def mass (T : Module.End K K[X]) : ℕ := ((symbol T).support.image grade).card

/-- The weight vector of the direction `(ρ, σ)`. -/
def wt (ρ σ : ℤ) : Fin 2 → ℤ := ![ρ, σ]

/-- `v_{ρ,σ}(T)`: the maximal `(ρ, σ)`-weight of the PBW support (junk value `0` for `T = 0`). -/
noncomputable def vDeg (ρ σ : ℤ) (T : Module.End K K[X]) : ℤ :=
  WithBot.unbotD 0 (MvPolynomial.weightedTotalDegree' (wt ρ σ) (symbol T))

/-- `ℓ_{ρ,σ}(T)`: the leading form of the PBW symbol in the direction `(ρ, σ)`. -/
noncomputable def leadingForm (ρ σ : ℤ) (T : Module.End K K[X]) : MvPolynomial (Fin 2) K :=
  MvPolynomial.weightedHomogeneousComponent (wt ρ σ) (vDeg ρ σ T) (symbol T)

/-- A direction with positive sum: `gcd(ρ, σ) = 1` and `ρ + σ > 0`. -/
def IsDirection (ρ σ : ℤ) : Prop := Int.gcd ρ σ = 1 ∧ 0 < ρ + σ

/-- `(ρ, σ) ∈ Dir(T)`: the leading form has at least two monomials. -/
def InDir (ρ σ : ℤ) (T : Module.End K K[X]) : Prop := 1 < (leadingForm ρ σ T).support.card

/-- A strict crossing face: a face whose starting grade (the maximal grade on the face) is
positive and whose ending grade (the minimal grade on the face) is negative. -/
def IsStrictCrossing (ρ σ : ℤ) (T : Module.End K K[X]) : Prop :=
  InDir ρ σ T ∧ (∃ d ∈ (leadingForm ρ σ T).support, 0 < grade d) ∧
    (∃ d ∈ (leadingForm ρ σ T).support, grade d < 0)

/-- The total degree `deg T = v_{1,1}(T)` in the PBW generators. -/
noncomputable def totalDeg (T : Module.End K K[X]) : ℕ := (symbol T).totalDegree

/-- The Poisson bracket `{a, b} = a_y b_x - a_x b_y`, the leading-bracket convention for
`[Y, X] = 1`. -/
noncomputable def poisson (a b : MvPolynomial (Fin 2) K) : MvPolynomial (Fin 2) K :=
  MvPolynomial.pderiv 1 a * MvPolynomial.pderiv 0 b - MvPolynomial.pderiv 0 a * MvPolynomial.pderiv 1 b

/-- The Fourier exchange `X ↦ Y, Y ↦ -X`, applied to the PBW expansion of an operator. -/
noncomputable def fourier (T : Module.End K K[X]) : Module.End K K[X] :=
  ∑ᶠ p : ℕ × ℕ, pbwCoeff T p.1 p.2 • ((-1 : K) ^ p.2 • (yOp K ^ p.1 * xOp K ^ p.2))

/-- The univariate cut polynomial `𝔣(z) = ℓ_{ρ,σ}(T)(1, z)` of the face. -/
noncomputable def cutPoly (ρ σ : ℤ) (T : Module.End K K[X]) : K[X] :=
  MvPolynomial.eval₂ Polynomial.C (fun i : Fin 2 => if i = 0 then 1 else Polynomial.X)
    (leadingForm ρ σ T)

/-- The largest multiplicity of a root of a polynomial (zero for a polynomial without roots). -/
noncomputable def maxRootMult (p : K[X]) : ℕ := by
  classical exact p.roots.toFinset.sup fun a => rootMultiplicity a p

end Symbols

section Pairs

/-- A counterexample pair: `[Q, P] = 1` and `P, Q` do not generate `A₁(ℂ)`. -/
def IsCounterexamplePair (P Q : A1 ℂ) : Prop := Q * P - P * Q = 1 ∧ Algebra.adjoin ℂ {P, Q} ≠ ⊤

/-- The total-degree leading symbol has two distinct nonzero roots:
`ℓ_{1,1}(T) = λ (y - α x)^u (y - β x)^v`. -/
def TwoRootTotalSymbol (T : Module.End ℂ ℂ[X]) : Prop :=
  ∃ (lam α β : ℂ) (u v : ℕ), lam ≠ 0 ∧ α ≠ 0 ∧ β ≠ 0 ∧ α ≠ β ∧ 1 ≤ u ∧ 1 ≤ v ∧
    leadingForm 1 1 T = MvPolynomial.C lam * (MvPolynomial.X 1 - MvPolynomial.C α * MvPolynomial.X 0) ^ u
      * (MvPolynomial.X 1 - MvPolynomial.C β * MvPolynomial.X 0) ^ v

/-- The three alternatives of the case reduction. -/
def CaseAlternative (T : Module.End ℂ ℂ[X]) : Prop :=
  (∃ ρ σ : ℤ, 0 < ρ ∧ -ρ < σ ∧ σ ≤ 0 ∧ Int.gcd ρ σ = 1 ∧ IsStrictCrossing ρ σ T) ∨
    10 ≤ mass T ∨ TwoRootTotalSymbol T

end Pairs

end Dixmier.Weyl
