/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module

public import DixmierFormal.Weyl.FieldSpanDescent
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

namespace Dixmier.Weyl
noncomputable section

variable (K L : Type*) [Field K] [Field L] [Algebra K L] [CharZero K]

/-- Every word in the images of source operators is the image of a source word. -/
theorem submonoid_closure_baseChange_lift (s : Set (A1 K))
    (z : A1 L) (hz : z ∈ Submonoid.closure (concreteBaseChange K L '' s)) :
    ∃ w : A1 K, w ∈ Submonoid.closure s ∧ concreteBaseChange K L w = z := by
  induction hz using Submonoid.closure_induction with
  | mem z hz =>
    obtain ⟨w, hw, rfl⟩ := hz
    exact ⟨w, Submonoid.subset_closure hw, rfl⟩
  | one => exact ⟨1, Submonoid.one_mem _, map_one _⟩
  | mul x y hx hy ihx ihy =>
    obtain ⟨u, hu, rfl⟩ := ihx
    obtain ⟨v, hv, rfl⟩ := ihy
    exact ⟨u * v, Submonoid.mul_mem _ hu hv, map_mul _ _ _⟩

/-- Membership in the algebra generated by source operators descends through a field
extension. The extension field may be arbitrarily large. -/
theorem adjoin_mem_descends (s : Set (A1 K)) (T : A1 K)
    (h : concreteBaseChange K L T ∈
      Algebra.adjoin L (concreteBaseChange K L '' s)) :
    T ∈ Algebra.adjoin K s := by
  letI : CharZero L := charZero_of_injective_algebraMap
    (FaithfulSMul.algebraMap_injective K L)
  have hs : concreteBaseChange K L T ∈
      Submodule.span L (Submonoid.closure (concreteBaseChange K L '' s) : Set (A1 L)) := by
    rw [← Algebra.adjoin_eq_span]
    exact h
  obtain ⟨a, t, ht, -, hsum⟩ := Submodule.mem_span_iff_exists_finset_subset.mp hs
  let w : t → A1 K := fun z =>
    Classical.choose (submonoid_closure_baseChange_lift K L s z.1 (ht z.2))
  have hw (z : t) : w z ∈ Submonoid.closure s :=
    (Classical.choose_spec (submonoid_closure_baseChange_lift K L s z.1 (ht z.2))).1
  have hmapw (z : t) : concreteBaseChange K L (w z) = z.1 :=
    (Classical.choose_spec (submonoid_closure_baseChange_lift K L s z.1 (ht z.2))).2
  have hsum' : (∑ z : t, a z.1 • concreteBaseChange K L (w z)) =
      concreteBaseChange K L T := by
    simp_rw [hmapw]
    calc
      (∑ z : t, a z.1 • z.1) = ∑ z ∈ t, a z • z := by
        rw [Finset.univ_eq_attach]
        exact Finset.sum_attach t (fun z => a z • z)
      _ = concreteBaseChange K L T := hsum
  obtain ⟨b, hb⟩ := finite_weyl_span_descends K L w T ⟨fun z => a z.1, hsum'⟩
  rw [← hb]
  apply Subalgebra.sum_mem
  intro z hz
  apply Subalgebra.smul_mem
  rw [← Subalgebra.mem_toSubmodule, Algebra.adjoin_eq_span]
  exact Submodule.subset_span (hw z)

theorem adjoin_eq_top_descends (s : Set (A1 K))
    (h : Algebra.adjoin L (concreteBaseChange K L '' s) = ⊤) :
    Algebra.adjoin K s = ⊤ := by
  apply top_unique
  intro T hT
  apply adjoin_mem_descends K L s T
  rw [h]
  trivial

/-- If a pair generates after extension of coefficients, it already generates over the
source field. No restriction on either operator's order or mass is imposed. -/
theorem pair_generation_descends (P Q : A1 K)
    (h : Algebra.adjoin L
      {concreteBaseChange K L P, concreteBaseChange K L Q} = ⊤) :
    Algebra.adjoin K {P, Q} = ⊤ := by
  have hs : concreteBaseChange K L '' ({P, Q} : Set (A1 K)) =
      {concreteBaseChange K L P, concreteBaseChange K L Q} := by
    ext T
    simp [eq_comm]
  apply adjoin_eq_top_descends K L {P, Q}
  simpa only [hs] using h

end
end Dixmier.Weyl
