/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module

public import Mathlib.SetTheory.Cardinal.Subfield
public import Mathlib.Algebra.Algebra.Rat
public import Mathlib.Data.Rat.Encodable
public import Mathlib.FieldTheory.IsAlgClosed.Classification
public import Mathlib.RingTheory.AlgebraicIndependent.Adjoin
public import Mathlib.Analysis.Complex.Polynomial.Basic
public import Mathlib.Analysis.Real.Cardinality
public import DixmierFormal.Weyl.Validation

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

namespace Dixmier.Weyl
open Polynomial
open scoped Cardinal
universe u

/-- A subfield generated by a countable set is countable, including when the ambient
field is uncountable. -/
theorem countable_subfield_closure {K : Type*} [DivisionRing K]
    (s : Set K) (hs : s.Countable) : Countable (Subfield.closure s) := by
  apply Cardinal.mk_le_aleph0_iff.mp
  calc
    Cardinal.mk (Subfield.closure s) ≤ max (Cardinal.mk s) ℵ₀ :=
      Subfield.cardinalMk_closure_le_max s
    _ = ℵ₀ := max_eq_right hs.le_aleph0

/-- Adjoining finitely many elements to the prime subfield of a characteristic-zero
field still gives a countable field. -/
theorem countable_ratSubfield_adjoin_finset {K : Type*} [Field K] [CharZero K]
    (s : Finset K) :
    Countable (Subfield.closure ((s : Set K) ∪ Set.range (algebraMap ℚ K))) := by
  apply countable_subfield_closure
  exact s.finite_toSet.countable.union (Set.countable_range (algebraMap ℚ K))

/-- The PBW coefficients of any two Weyl operators lie in one countable subfield
generated by finitely many elements over `ℚ`. -/
theorem exists_countable_ratSubfield_for_pair {K : Type*} [Field K] [CharZero K]
    (P Q : A1 K) :
    ∃ (E : Subfield K) (c d : (ℕ × ℕ) →₀ K), Countable E ∧
      c.sum (fun p a => a • normalOrderedMonomial (K := K) p.1 p.2) =
        (P : Module.End K K[X]) ∧
      d.sum (fun p a => a • normalOrderedMonomial (K := K) p.1 p.2) =
        (Q : Module.End K K[X]) ∧
      (∀ p ∈ c.support, c p ∈ E) ∧ (∀ p ∈ d.support, d p ∈ E) := by
  classical
  obtain ⟨c, hc⟩ := A1_exists_finiteNormalOrderedExpansion P
  obtain ⟨d, hd⟩ := A1_exists_finiteNormalOrderedExpansion Q
  let coeffs : Finset K := c.support.image c ∪ d.support.image d
  let E : Subfield K := Subfield.closure
    ((coeffs : Set K) ∪ Set.range (algebraMap ℚ K))
  refine ⟨E, c, d, ?_, hc, hd, ?_, ?_⟩
  · exact countable_ratSubfield_adjoin_finset coeffs
  · intro p hp
    apply Subfield.subset_closure
    apply Set.mem_union_left
    change c p ∈ c.support.image c ∪ d.support.image d
    apply Finset.mem_union_left
    exact Finset.mem_image.mpr ⟨p, hp, rfl⟩
  · intro p hp
    apply Subfield.subset_closure
    apply Set.mem_union_left
    change d p ∈ c.support.image c ∪ d.support.image d
    apply Finset.mem_union_right
    exact Finset.mem_image.mpr ⟨p, hp, rfl⟩


/-- Every countable characteristic-zero field admits a field embedding into `ℂ` that
fixes the rational numbers. Choose a transcendence basis, map its countable index set
into a transcendence basis of `ℂ`, identify the corresponding rational-function fields,
and extend across the algebraic part using algebraic closedness. -/
theorem exists_algHom_to_complex_of_countable {K : Type u} [Field K] [CharZero K]
    [Countable K] : Nonempty (K →ₐ[ℚ] ℂ) := by
  obtain ⟨s, hs⟩ := exists_isTranscendenceBasis ℚ K
  obtain ⟨t, ht⟩ := exists_isTranscendenceBasis ℚ ℂ
  have hcount_s : Countable s := Subtype.val_injective.countable
  have hs_le : #s ≤ ℵ₀ := Cardinal.mk_le_aleph0_iff.mpr hcount_s
  have hC : ℵ₀ < #ℂ :=
    Cardinal.aleph0_lt_mk_iff.mpr Complex.ofReal_injective.uncountable
  have hQ : #(ℚ) ≤ ℵ₀ := Cardinal.mk_le_aleph0_iff.mpr inferInstance
  have ht_card : #ℂ = #t :=
    IsAlgClosed.cardinal_eq_cardinal_transcendence_basis_of_aleph0_lt'
      (v' := Subtype.val) ht hQ hC
  have ht_large : ℵ₀ ≤ #t := by rw [← ht_card]; exact Cardinal.aleph0_le_mk ℂ
  have hs_t : Cardinal.lift.{0, u} #s ≤ Cardinal.lift.{u, 0} #t := by
    calc
      Cardinal.lift.{0, u} #s ≤ Cardinal.lift.{0, u} ℵ₀ :=
        (Cardinal.lift_le).2 hs_le
      _ = ℵ₀ := by simp
      _ = Cardinal.lift.{u, 0} ℵ₀ := by simp
      _ ≤ Cardinal.lift.{u, 0} #t := (Cardinal.lift_le).2 ht_large
  obtain ⟨e⟩ := (@Cardinal.lift_mk_le.{0, u, 0} s t).1 hs_t
  let L := IntermediateField.adjoin ℚ (Set.range (Subtype.val : s → K))
  let zvals : s → ℂ := fun i => e i
  let M := IntermediateField.adjoin ℚ (Set.range zvals)
  let z : s → M := fun i =>
    ⟨zvals i, IntermediateField.subset_adjoin ℚ (Set.range zvals) (Set.mem_range_self i)⟩
  have hz_comp : (IntermediateField.val M) ∘ z = (fun i : s => (e i : ℂ)) := by
    funext i
    rfl
  have hz_ind : AlgebraicIndependent ℚ z := by
    apply AlgebraicIndependent.of_comp (IntermediateField.val M)
    rw [hz_comp]
    exact ht.1.comp e e.injective
  let frac := FractionRing (MvPolynomial s ℚ)
  letI : Algebra ℚ frac := OreLocalization.instAlgebra
  let psi : frac →ₐ[ℚ] M :=
    IsFractionRing.liftAlgHom (g := MvPolynomial.aeval z) hz_ind
  let phi : L →ₐ[ℚ] ℂ :=
    (IntermediateField.val M).comp (psi.comp hs.1.reprField)
  letI : Algebra.IsAlgebraic L K := hs.isAlgebraic_field
  obtain ⟨extension, _⟩ :=
    IsAlgClosed.surjective_domRestrict_of_isAlgebraic (K := ℚ) (L := L) (E := K)
      (M := ℂ) phi
  exact ⟨extension⟩

end Dixmier.Weyl
