/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module

public import DixmierFormal.Weyl.PositiveGradeNormalForms

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

/-!
# The centralizer of the derivative generator

The first step is the exact commutator of `Y` with one normal-ordered PBW monomial.
It will be extended coefficientwise to a finite PBW expansion.
-/

namespace Dixmier.Weyl

open Polynomial

variable {K : Type*} [Field K]

/-- Commuting `Y` past `X^i Y^j` differentiates its `X` factor. -/
theorem yOp_commutator_normalOrderedMonomial (i j : ℕ) :
    yOp K * normalOrderedMonomial (K := K) i j -
      normalOrderedMonomial (K := K) i j * yOp K =
      ((i : K) • normalOrderedMonomial (K := K) (i - 1) j) := by
  cases i with
  | zero =>
      have hpow : yOp K ^ j * yOp K = yOp K * yOp K ^ j := by
        rw [← pow_succ, ← pow_succ']
      simp [normalOrderedMonomial, hpow]
  | succ i =>
      have hpow : yOp K ^ j * yOp K = yOp K * yOp K ^ j := by
        rw [← pow_succ, ← pow_succ']
      change yOp K * (xOp K ^ (i + 1) * yOp K ^ j) -
          (xOp K ^ (i + 1) * yOp K ^ j) * yOp K =
        (((i + 1 : ℕ) : K) • (xOp K ^ i * yOp K ^ j))
      rw [← mul_assoc, yOp_mul_xOp_pow_succ, add_mul]
      rw [smul_mul_assoc]
      simp only [mul_assoc, hpow, add_sub_cancel_left, Nat.cast_succ]

private theorem pbwCoeff_finset_sum [CharZero K]
    (s : Finset (ℕ × ℕ)) (F : (ℕ × ℕ) → Module.End K K[X]) (i j : ℕ) :
    pbwCoeff (∑ p ∈ s, F p) i j = ∑ p ∈ s, pbwCoeff (F p) i j := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [pbwCoeff, coeffPoly]
  | insert p s hp ih =>
      simp only [Finset.sum_insert hp]
      rw [pbwCoeff_add, ih]

/-- The coefficient of `[Y,R]` at `X^iY^j` is `(i+1)` times the coefficient
of `R` at `X^(i+1)Y^j`. -/
theorem yOp_commutator_pbwCoeff [CharZero K] (R : A1 K) (i j : ℕ) :
    pbwCoeff (yOp K * (R : Module.End K K[X]) -
      (R : Module.End K K[X]) * yOp K) i j =
      ((i + 1 : ℕ) : K) * pbwCoeff (R : Module.End K K[X]) (i + 1) j := by
  classical
  obtain ⟨c, hc⟩ := A1_exists_finiteNormalOrderedExpansion R
  have hcoeff : pbwCoeff (R : Module.End K K[X]) (i + 1) j = c (i + 1, j) := by
    rw [← hc]
    exact pbwCoeff_finsuppNormalOrderedSum c (i + 1) j
  have hcomm : yOp K * (R : Module.End K K[X]) -
      (R : Module.End K K[X]) * yOp K =
      ∑ p ∈ c.support, c p •
        (yOp K * normalOrderedMonomial (K := K) p.1 p.2 -
          normalOrderedMonomial (K := K) p.1 p.2 * yOp K) := by
    rw [← hc, Finsupp.sum, Finset.mul_sum, Finset.sum_mul]
    rw [← Finset.sum_sub_distrib]
    apply Finset.sum_congr rfl
    intro p hp
    rw [mul_smul_comm, smul_mul_assoc, smul_sub]
  rw [hcomm, pbwCoeff_finset_sum, hcoeff]
  simp_rw [yOp_commutator_normalOrderedMonomial, smul_smul, pbwCoeff_smul]
  simp only [normalOrderedMonomial, pbwCoeff_normalOrdered_monomial]
  by_cases hmem : (i + 1, j) ∈ c.support
  · rw [Finset.sum_eq_single (i + 1, j)]
    · simp [Nat.cast_succ, mul_comm]
    · intro p hp hne
      by_cases hp0 : p.1 = 0
      · simp [hp0]
      · have hpos : 0 < p.1 := Nat.pos_of_ne_zero hp0
        have hnot : ¬ (i = p.1 - 1 ∧ j = p.2) := by
          rintro ⟨hi, hj⟩
          apply hne
          apply Prod.ext
          · omega
          · exact hj.symm
        simp [hnot]
    · simp [hmem]
  · have hzero : c (i + 1, j) = 0 := by simpa using hmem
    rw [hzero, mul_zero]
    apply Finset.sum_eq_zero
    intro p hp
    by_cases hp0 : p.1 = 0
    · simp [hp0]
    · have hpos : 0 < p.1 := Nat.pos_of_ne_zero hp0
      have hnot : ¬ (i = p.1 - 1 ∧ j = p.2) := by
        rintro ⟨hi, hj⟩
        apply hmem
        have heq : p = (i + 1, j) := by
          apply Prod.ext
          · omega
          · exact hj.symm
        simpa [heq] using hp
      simp [hnot]

/-- An operator commuting with `Y` has no positive `X` exponent in its PBW expansion. -/
theorem pbwCoeff_pos_x_eq_zero_of_commutes_y [CharZero K] (R : A1 K)
    (hcomm : yOp K * (R : Module.End K K[X]) -
      (R : Module.End K K[X]) * yOp K = 0) (i j : ℕ) :
    pbwCoeff (R : Module.End K K[X]) (i + 1) j = 0 := by
  have h := yOp_commutator_pbwCoeff R i j
  rw [hcomm] at h
  have hz : pbwCoeff (0 : Module.End K K[X]) i j = 0 := by
    simp [pbwCoeff, coeffPoly]
  rw [hz] at h
  have hi : ((i + 1 : ℕ) : K) ≠ 0 := Nat.cast_ne_zero.mpr (Nat.succ_ne_zero i)
  exact (mul_eq_zero.mp h.symm).resolve_left hi

/-- The centralizer of the derivative generator inside the polynomial Weyl algebra
is the one-generator subalgebra generated by that derivative. -/
theorem mem_adjoin_y_of_commutes_y [CharZero K] (R : A1 K)
    (hcomm : yOp K * (R : Module.End K K[X]) -
      (R : Module.End K K[X]) * yOp K = 0) :
    R ∈ Algebra.adjoin K
      ({(⟨yOp K, yOp_mem_A1⟩ : A1 K)} : Set (A1 K)) := by
  classical
  obtain ⟨c, hc⟩ := A1_exists_finiteNormalOrderedExpansion R
  have hsupport : ∀ p ∈ c.support, p.1 = 0 := by
    rintro ⟨a, b⟩ hp
    by_contra hne
    have ha : 0 < a := Nat.pos_of_ne_zero hne
    obtain ⟨i, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hne
    have hz := pbwCoeff_pos_x_eq_zero_of_commutes_y R hcomm i b
    rw [← hc, pbwCoeff_finsuppNormalOrderedSum] at hz
    exact (Finsupp.mem_support_iff.mp hp) hz
  let yA : A1 K := ⟨yOp K, yOp_mem_A1⟩
  have hR : R = ∑ p ∈ c.support, c p • yA ^ p.2 := by
    apply Subtype.ext
    rw [← hc, Finsupp.sum]
    simp only [AddSubmonoidClass.coe_finsetSum, SetLike.val_smul,
      SubmonoidClass.coe_pow]
    apply Finset.sum_congr rfl
    intro p hp
    have hp0 := hsupport p hp
    simp [normalOrderedMonomial, yA, hp0]
  rw [hR]
  apply Subalgebra.sum_mem
  intro p hp
  let S := Algebra.adjoin K ({yA} : Set (A1 K))
  have hy : yA ∈ S := Algebra.subset_adjoin (by simp)
  exact S.smul_mem (S.pow_mem hy p.2) (c p)

end Dixmier.Weyl
