module

public import DixmierFormal.Weyl.JosephCommutatorChain

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

/-!
# Local nilpotence on an exact pair's generated algebra

Repeated commutation with P terminates on every element of the algebra
 generated by P,Q when [Q,P]=1. This removes the termination premise from
 the two-bracket extraction theorem without restricting the mate.
-/
set_option maxHeartbeats 0
namespace Dixmier.Weyl
open MvPolynomial Polynomial

private theorem chain_zero (P : A1 ℂ) (n : ℕ) :
    josephCommutatorChain P 0 n = 0 := by
  induction n with
  | zero => rfl
  | succ n ih =>
    rw [josephCommutatorChain,ih]
    apply Subtype.ext
    change P.1*0-0*P.1=(0 : Module.End ℂ ℂ[X])
    simp

private theorem chain_add (P R S : A1 ℂ) (n : ℕ) :
    josephCommutatorChain P (R+S) n =
      josephCommutatorChain P R n + josephCommutatorChain P S n := by
  induction n with
  | zero => rfl
  | succ n ih =>
    simp only [josephCommutatorChain,ih]
    noncomm_ring

private theorem chain_comp (P R : A1 ℂ) (n m : ℕ) :
    josephCommutatorChain P R (n+m) =
      josephCommutatorChain P (josephCommutatorChain P R m) n := by
  induction n with
  | zero => simp only [Nat.zero_add,josephCommutatorChain]
  | succ n ih => simp only [Nat.succ_add,josephCommutatorChain,ih]

private theorem chain_shift (P R : A1 ℂ) (n : ℕ) :
    josephCommutatorChain P (P*R-R*P) n = josephCommutatorChain P R (n+1) := by
  exact (chain_comp P R n 1).symm

/-- A product is killed after the sum of any two killing bounds. -/
theorem joseph_chain_mul_termination_bound (P R S : A1 ℂ) (n m : ℕ)
    (hR : josephCommutatorChain P R n = 0)
    (hS : josephCommutatorChain P S m = 0) :
    josephCommutatorChain P (R*S) (n+m) = 0 := by
  induction n generalizing R S m with
  | zero =>
    have hz : R=0 := hR
    simp [hz,chain_zero]
  | succ n ihn =>
    induction m generalizing S with
    | zero =>
      have hz : S=0 := hS
      simp [hz,chain_zero]
    | succ m ihm =>
      have hDR : josephCommutatorChain P (P*R-R*P) n=0 := by
        rw [chain_shift]; exact hR
      have hDS : josephCommutatorChain P (P*S-S*P) m=0 := by
        rw [chain_shift]; exact hS
      have hleft := ihn (P*R-R*P) S (m+1) hDR hS
      have hright := ihm (P*S-S*P) hDS
      have hleib : P*(R*S)-(R*S)*P=(P*R-R*P)*S+R*(P*S-S*P) := by
        apply Subtype.ext
        change P.1*(R.1*S.1)-(R.1*S.1)*P.1=
          (P.1*R.1-R.1*P.1)*S.1+R.1*(P.1*S.1-S.1*P.1)
        apply LinearMap.ext
        intro f
        change P.1 (R.1 (S.1 f)) - R.1 (S.1 (P.1 f)) =
          (P.1 (R.1 (S.1 f)) - R.1 (P.1 (S.1 f))) +
            R.1 (P.1 (S.1 f) - S.1 (P.1 f))
        rw [map_sub]
        abel
      have hindex : (n+1)+(m+1)=(n+(m+1))+1 := by omega
      rw [hindex,← chain_shift,hleib,chain_add,hleft]
      have hi : n+(m+1)=(n+1)+m := by omega
      rw [hi,hright,add_zero]

/-- Exact pair generation implies local nilpotence of the inner derivation. -/
theorem joseph_chain_terminates_on_adjoin
    (P Q R : A1 ℂ) (hpair : Q*P-P*Q=1)
    (hR : R ∈ Algebra.adjoin ℂ {P,Q}) :
    ∃ n, josephCommutatorChain P R n=0 := by
  refine Algebra.adjoin_induction (p := fun T _ => ∃ n, josephCommutatorChain P T n=0)
    ?_ ?_ ?_ ?_ hR
  · intro T hT
    simp only [Set.mem_insert_iff,Set.mem_singleton_iff] at hT
    rcases hT with hT | hT
    · rw [hT]
      refine ⟨1,?_⟩
      apply Subtype.ext
      change P.1*P.1-P.1*P.1=(0 : Module.End ℂ ℂ[X])
      exact sub_self _
    · rw [hT]
      refine ⟨2,?_⟩
      have hb : P*Q-Q*P = -1 := by
        calc
          P*Q-Q*P = -(Q*P-P*Q) := by abel
          _ = -1 := by rw [hpair]
      simp only [josephCommutatorChain,hb]
      apply Subtype.ext
      change P.1*(-1)-(-1)*P.1=(0 : Module.End ℂ ℂ[X])
      ext f
      simp [Module.End.mul_apply]
  · intro c
    refine ⟨1,?_⟩
    change P*algebraMap ℂ (A1 ℂ) c-algebraMap ℂ (A1 ℂ) c*P=0
    exact sub_eq_zero.mpr (Algebra.commutes c P).symm
  · intro T U _ _ hT hU
    obtain ⟨n,hn⟩ := hT
    obtain ⟨m,hm⟩ := hU
    refine ⟨n+m,?_⟩
    rw [chain_add]
    have ht : josephCommutatorChain P T (n+m)=0 := by
      rw [Nat.add_comm,chain_comp,hn,chain_zero]
    have hu : josephCommutatorChain P U (n+m)=0 := by
      rw [chain_comp,hm,chain_zero]
    rw [ht,hu,add_zero]
  · intro T U _ _ hT hU
    obtain ⟨n,hn⟩ := hT
    obtain ⟨m,hm⟩ := hU
    exact ⟨n+m,joseph_chain_mul_termination_bound P T U n m hn hm⟩

/-- Only the initial nonzero symbol bracket remains in this witness extraction. -/
theorem joseph_two_bracket_of_generated_nonzero_bracket
    (P Q R : A1 ℂ) (hpair : Q*P-P*Q=1) (ρ σ : ℤ)
    (hweight : 0<ρ+σ) (hR : R ∈ Algebra.adjoin ℂ {P,Q})
    (hfirst : poisson (leadingForm ρ σ P.1) (leadingForm ρ σ R.1) ≠ 0) :
    ∃ T : A1 ℂ, T ∈ Algebra.adjoin ℂ {P,Q} ∧
      poisson (leadingForm ρ σ P.1) (leadingForm ρ σ T.1) ≠ 0 ∧
      poisson (leadingForm ρ σ P.1)
        (poisson (leadingForm ρ σ P.1) (leadingForm ρ σ T.1))=0 :=
  joseph_two_bracket_of_terminating_chain P Q R ρ σ hweight hR hfirst
    (joseph_chain_terminates_on_adjoin P Q R hpair hR)

end Dixmier.Weyl
