/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module

public import DixmierFormal.Weyl.RamifiedNormalForm

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

/-!
# Unique finite PBW coefficients in the ramified operator algebra

For positive ramification index `l`, each operator generated by Laurent
coefficient multiplication and `Y=d/dX` has a unique finite expansion
`∑ n, M_(a_n) Y^n`. The uniqueness proof applies the operator to
`1,X,X²,…`, using `Y^k(X^k)=k!` and `Y^j(X^k)=0` for `j>k`.
This supplies canonical coefficient and order data for the G13 cut;
the cut itself is still an open formalization obligation.
-/
namespace Dixmier.Weyl
open LaurentPolynomial

/-- The scaled derivative sends `X=T^l` to one. -/
theorem ramifiedDerivative_X (l : ℕ) (hl : 0 < l) :
    ramifiedDerivative l (T (l : ℤ)) = (1 : LaurentPolynomial ℂ) := by
  rw [ramifiedDerivative_T]
  have hln : (l : ℂ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hl)
  simp [hln, LaurentPolynomial.T_zero]

theorem ramifiedDerivative_X_pow (l : ℕ) (hl : 0 < l) (k : ℕ) :
    ramifiedDerivative l ((T (l : ℤ) : LaurentPolynomial ℂ)^k) =
      (k : ℂ) • (T (l : ℤ) : LaurentPolynomial ℂ)^(k-1) := by
  change (ramifiedDerivation l) ((T (l : ℤ) : LaurentPolynomial ℂ)^k) = _
  rw [(ramifiedDerivation l).leibniz_pow]
  change k • (T (l : ℤ) : LaurentPolynomial ℂ)^(k-1) •
    ramifiedDerivative l (T (l : ℤ)) = _
  rw [ramifiedDerivative_X l hl]
  simp only [smul_eq_mul, mul_one, Nat.cast_smul_eq_nsmul]

theorem ramifiedDerivative_pow_X_pow_diag (l : ℕ) (hl : 0 < l) (k : ℕ) :
    ((ramifiedDerivative l)^k) ((T (l : ℤ) : LaurentPolynomial ℂ)^k) =
      (k.factorial : ℂ) • (1 : LaurentPolynomial ℂ) := by
  induction k with
  | zero => simp
  | succ k ih =>
      rw [pow_succ]
      change ((ramifiedDerivative l)^k)
        (ramifiedDerivative l ((T (l : ℤ) : LaurentPolynomial ℂ)^(k+1))) = _
      rw [ramifiedDerivative_X_pow l hl]
      simp only [Nat.add_sub_cancel, map_smul]
      rw [ih]
      simp [Nat.factorial_succ, mul_smul]

theorem ramifiedDerivative_pow_X_pow_zero (l : ℕ) (hl : 0 < l)
    (k j : ℕ) (hjk : k < j) :
    ((ramifiedDerivative l)^j) ((T (l : ℤ) : LaurentPolynomial ℂ)^k) = 0 := by
  induction k generalizing j with
  | zero =>
      have hj : 0 < j := by omega
      obtain ⟨r, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hj)
      rw [pow_succ]
      change ((ramifiedDerivative l)^r) (ramifiedDerivative l (1 : LaurentPolynomial ℂ)) = 0
      have hderiv_one : ramifiedDerivative l (1 : LaurentPolynomial ℂ) = 0 := by
        have h := ramifiedDerivative_X_pow l hl 0
        simpa using h
      rw [hderiv_one]
      simp
  | succ k ih =>
      have hj : 0 < j := by omega
      obtain ⟨r, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hj)
      rw [pow_succ]
      change ((ramifiedDerivative l)^r)
        (ramifiedDerivative l ((T (l : ℤ) : LaurentPolynomial ℂ)^(k+1))) = 0
      rw [ramifiedDerivative_X_pow l hl]
      simp only [Nat.add_sub_cancel, map_smul]
      rw [ih r (by omega)]
      simp

noncomputable def ramifiedNormalEval (l : ℕ)
    (a : ℕ →₀ LaurentPolynomial ℂ) :
    Module.End ℂ (LaurentPolynomial ℂ) :=
  a.sum fun j f => ramifiedCoeffMul f * (ramifiedDerivative l)^j

theorem ramifiedNormalEval_apply (l : ℕ)
    (a : ℕ →₀ LaurentPolynomial ℂ) (g : LaurentPolynomial ℂ) :
    ramifiedNormalEval l a g =
      a.sum (fun j f => f * ((ramifiedDerivative l)^j) g) := by
  simp [ramifiedNormalEval, Finsupp.sum, Finset.sum_apply, ramifiedCoeffMul]

theorem ramifiedNormalEval_zero_coeff (l : ℕ) (hl : 0 < l)
    (a : ℕ →₀ LaurentPolynomial ℂ)
    (hzero : ramifiedNormalEval l a = 0) (k : ℕ) : a k = 0 := by
  induction k using Nat.strong_induction_on with
  | h k ih =>
      by_cases hk : k ∈ a.support
      · have hsum : (∑ j ∈ a.support,
            a j * ((ramifiedDerivative l)^j)
              ((T (l : ℤ) : LaurentPolynomial ℂ)^k)) = 0 := by
          have happ := congrArg
            (fun U : Module.End ℂ (LaurentPolynomial ℂ) =>
              U ((T (l : ℤ) : LaurentPolynomial ℂ)^k)) hzero
          simpa [ramifiedNormalEval_apply, Finsupp.sum] using happ
        have hsingle : (∑ j ∈ a.support,
            a j * ((ramifiedDerivative l)^j)
              ((T (l : ℤ) : LaurentPolynomial ℂ)^k)) =
            a k * ((ramifiedDerivative l)^k)
              ((T (l : ℤ) : LaurentPolynomial ℂ)^k) := by
          apply Finset.sum_eq_single k
          · intro j hj hjne
            rcases lt_or_gt_of_ne hjne with hjlt | hjgt
            · rw [ih j hjlt, zero_mul]
            · rw [ramifiedDerivative_pow_X_pow_zero l hl k j hjgt, mul_zero]
          · intro hnot
            exact (hnot hk).elim
        rw [hsingle, ramifiedDerivative_pow_X_pow_diag l hl k] at hsum
        have hfac : (k.factorial : ℂ) ≠ 0 := by exact_mod_cast Nat.factorial_ne_zero k
        simpa [smul_eq_mul, mul_assoc, hfac] using hsum
      · simpa only [Finsupp.mem_support_iff, not_ne_iff] using hk

theorem ramifiedCoeffMul_sub (f g : LaurentPolynomial ℂ) :
    ramifiedCoeffMul (f-g) = ramifiedCoeffMul f - ramifiedCoeffMul g := by
  apply LinearMap.ext
  intro h
  change (f-g)*h = f*h-g*h
  rw [sub_mul]

theorem ramifiedNormalEval_sub (l : ℕ)
    (a b : ℕ →₀ LaurentPolynomial ℂ) :
    ramifiedNormalEval l (a-b) =
      ramifiedNormalEval l a - ramifiedNormalEval l b := by
  unfold ramifiedNormalEval
  rw [Finsupp.sum_sub_index]
  intro n f g
  rw [ramifiedCoeffMul_sub, sub_mul]

/-- A finite normal-ordered expansion is zero only when every coefficient
is zero. -/
theorem ramifiedNormalEval_injective (l : ℕ) (hl : 0 < l) :
    Function.Injective (ramifiedNormalEval l) := by
  intro a b hab
  have hzero : ramifiedNormalEval l (a-b) = 0 := by
    rw [ramifiedNormalEval_sub, hab, sub_self]
  apply Finsupp.ext
  intro k
  have hc := ramifiedNormalEval_zero_coeff l hl (a-b) hzero k
  simpa only [Finsupp.sub_apply, sub_eq_zero] using hc

noncomputable def ramifiedCoeffMulLinear :
    LaurentPolynomial ℂ →ₗ[ℂ] Module.End ℂ (LaurentPolynomial ℂ) where
  toFun := ramifiedCoeffMul
  map_add' f g := by
    apply LinearMap.ext
    intro h
    change (f+g)*h = f*h+g*h
    rw [add_mul]
  map_smul' c f := by
    apply LinearMap.ext
    intro h
    change (c • f)*h = c • (f*h)
    rw [smul_mul_assoc]

noncomputable def ramifiedNormalEvalLinear (l : ℕ) :
    (ℕ →₀ LaurentPolynomial ℂ) →ₗ[ℂ]
      Module.End ℂ (LaurentPolynomial ℂ) :=
  (Finsupp.lsum ℂ) (fun n =>
    (LinearMap.mulRight ℂ ((ramifiedDerivative l)^n)).comp
      ramifiedCoeffMulLinear)

theorem ramifiedNormalEvalLinear_apply (l : ℕ)
    (a : ℕ →₀ LaurentPolynomial ℂ) :
    ramifiedNormalEvalLinear l a = ramifiedNormalEval l a := by
  rfl

theorem ramifiedNormalEvalLinear_single (l : ℕ) (n : ℕ)
    (f : LaurentPolynomial ℂ) :
    ramifiedNormalEvalLinear l (Finsupp.single n f) =
      ramifiedCoeffMul f * (ramifiedDerivative l)^n := by
  change (Finsupp.single n f).sum (fun i x =>
    ramifiedCoeffMul x * (ramifiedDerivative l)^i) = _
  rw [Finsupp.sum_single_index]
  simp [ramifiedCoeffMul]

theorem ramifiedOperatorAlgebra_exists_coefficients (l : ℕ)
    (T : Module.End ℂ (LaurentPolynomial ℂ))
    (hT : T ∈ ramifiedOperatorAlgebra l) :
    ∃ a : ℕ →₀ LaurentPolynomial ℂ,
      ramifiedNormalEval l a = T := by
  have hspan : normalSpan l ≤ LinearMap.range (ramifiedNormalEvalLinear l) := by
    apply Submodule.span_le.mpr
    rintro U ⟨⟨f,n⟩,rfl⟩
    exact ⟨Finsupp.single n f, ramifiedNormalEvalLinear_single l n f⟩
  obtain ⟨a, ha⟩ := hspan (ramifiedOperatorAlgebra_normal l T hT)
  exact ⟨a, by simpa only [ramifiedNormalEvalLinear_apply] using ha⟩

/-- Existence and uniqueness of finite PBW coefficient sequences. -/
theorem ramifiedOperatorAlgebra_unique_coefficients (l : ℕ) (hl : 0 < l)
    (T : Module.End ℂ (LaurentPolynomial ℂ))
    (hT : T ∈ ramifiedOperatorAlgebra l) :
    ∃! a : ℕ →₀ LaurentPolynomial ℂ,
      ramifiedNormalEval l a = T := by
  obtain ⟨a,ha⟩ := ramifiedOperatorAlgebra_exists_coefficients l T hT
  refine ⟨a,ha,?_⟩
  intro b hb
  exact ramifiedNormalEval_injective l hl (hb.trans ha.symm)

end Dixmier.Weyl
