/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module

public import DixmierFormal.Weyl.RamifiedDerivation

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

/-!
# Ramified differential operators as an endomorphism algebra

This is the algebra generated by multiplication by Laurent coefficients in
`T=X^(1/l)` and the scaled derivative `Y=d/dX`. The exact normal-ordering
relation is proved below. A finite PBW expansion theorem, coefficient
uniqueness, and G13's ramified cut are not yet formalized.
-/

namespace Dixmier.Weyl

open LaurentPolynomial

noncomputable def ramifiedOperatorAlgebra (l : ℕ) :
    Subalgebra ℂ (Module.End ℂ (LaurentPolynomial ℂ)) :=
  Algebra.adjoin ℂ (Set.range ramifiedCoeffMul ∪ {ramifiedDerivative l})

theorem coeff_mem_ramifiedOperatorAlgebra (l : ℕ)
    (f : LaurentPolynomial ℂ) :
    ramifiedCoeffMul f ∈ ramifiedOperatorAlgebra l := by
  apply Algebra.subset_adjoin
  exact Or.inl ⟨f, rfl⟩

theorem derivative_mem_ramifiedOperatorAlgebra (l : ℕ) :
    ramifiedDerivative l ∈ ramifiedOperatorAlgebra l := by
  apply Algebra.subset_adjoin
  exact Or.inr (Set.mem_singleton_iff.mpr rfl)

/-- Exact normal-ordering rule for every ramified Laurent coefficient. -/
theorem ramified_normal_order (l : ℕ) (f : LaurentPolynomial ℂ) :
    ramifiedDerivative l * ramifiedCoeffMul f =
      ramifiedCoeffMul f * ramifiedDerivative l +
        ramifiedCoeffMul (ramifiedDerivative l f) := by
  have h := ramifiedDerivative_coeff_comm l f
  calc
    ramifiedDerivative l * ramifiedCoeffMul f =
        (ramifiedDerivative l * ramifiedCoeffMul f -
          ramifiedCoeffMul f * ramifiedDerivative l) +
          ramifiedCoeffMul f * ramifiedDerivative l := by abel
    _ = ramifiedCoeffMul f * ramifiedDerivative l +
          ramifiedCoeffMul (ramifiedDerivative l f) := by rw [h]; abel

theorem ramifiedX_mem (l : ℕ) :
    ramifiedX l ∈ ramifiedOperatorAlgebra l := by
  exact coeff_mem_ramifiedOperatorAlgebra l (T (l : ℤ))

end Dixmier.Weyl
