/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module

public import DixmierFormal.Weyl.RamifiedPBWData

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

/-!
# The shifted ramified derivative

For any Laurent coefficient `h`, the shifted generator `Y_h=Y+M_h`
has the same commutator with every coefficient multiplier, still obeys
`[Y_h,X]=1`, and generates the same operator algebra with the
coefficients. These are exact algebraic prerequisites for a shear.
An algebra automorphism acting on arbitrary operators, its PBW support
effect, and G13's cut remain separate proof obligations.
-/
namespace Dixmier.Weyl

/-- The candidate image of `Y` under a ramified shear. -/
noncomputable def ramifiedShiftedY (l : ℕ) (h : LaurentPolynomial ℂ) :
    Module.End ℂ (LaurentPolynomial ℂ) :=
  ramifiedDerivative l + ramifiedCoeffMul h

theorem ramifiedShiftedY_normal_order (l : ℕ)
    (h f : LaurentPolynomial ℂ) :
    ramifiedShiftedY l h * ramifiedCoeffMul f =
      ramifiedCoeffMul f * ramifiedShiftedY l h +
        ramifiedCoeffMul (ramifiedDerivative l f) := by
  have hcomm : ramifiedCoeffMul h * ramifiedCoeffMul f =
      ramifiedCoeffMul f * ramifiedCoeffMul h := by
    rw [ramifiedCoeffMul_mul, ramifiedCoeffMul_mul, mul_comm]
  dsimp [ramifiedShiftedY]
  rw [add_mul, mul_add, ramified_normal_order, hcomm]
  abel

/-- The operator algebra generated by coefficients and `Y+h`. -/
noncomputable def ramifiedShiftedAlgebra (l : ℕ) (h : LaurentPolynomial ℂ) :
    Subalgebra ℂ (Module.End ℂ (LaurentPolynomial ℂ)) :=
  Algebra.adjoin ℂ (Set.range ramifiedCoeffMul ∪ {ramifiedShiftedY l h})

theorem ramifiedShiftedAlgebra_eq (l : ℕ) (h : LaurentPolynomial ℂ) :
    ramifiedShiftedAlgebra l h = ramifiedOperatorAlgebra l := by
  apply le_antisymm
  · apply Algebra.adjoin_le
    rintro x (hx | hx)
    · rcases hx with ⟨f,rfl⟩
      exact coeff_mem_ramifiedOperatorAlgebra l f
    · have heq : x = ramifiedShiftedY l h := Set.mem_singleton_iff.mp hx
      subst x
      exact (ramifiedOperatorAlgebra l).add_mem
        (derivative_mem_ramifiedOperatorAlgebra l)
        (coeff_mem_ramifiedOperatorAlgebra l h)
  · apply Algebra.adjoin_le
    rintro x (hx | hx)
    · rcases hx with ⟨f,rfl⟩
      apply Algebra.subset_adjoin
      exact Or.inl ⟨f,rfl⟩
    · have heq : x = ramifiedDerivative l := Set.mem_singleton_iff.mp hx
      subst x
      have hshift : ramifiedShiftedY l h ∈ ramifiedShiftedAlgebra l h := by
        apply Algebra.subset_adjoin
        exact Or.inr (Set.mem_singleton_iff.mpr rfl)
      have hcoeff : ramifiedCoeffMul h ∈ ramifiedShiftedAlgebra l h := by
        apply Algebra.subset_adjoin
        exact Or.inl ⟨h,rfl⟩
      have hmem := (ramifiedShiftedAlgebra l h).sub_mem hshift hcoeff
      simpa [ramifiedShiftedY] using hmem

theorem ramifiedShiftedY_X_comm (l : ℕ) (hl : 0 < l)
    (h : LaurentPolynomial ℂ) :
    ramifiedShiftedY l h * ramifiedX l -
      ramifiedX l * ramifiedShiftedY l h = 1 := by
  have horder := ramifiedShiftedY_normal_order l h
    (LaurentPolynomial.T (l : ℤ))
  rw [ramifiedDerivative_X l hl, ramifiedCoeffMul_one] at horder
  change ramifiedShiftedY l h * ramifiedX l =
    ramifiedX l * ramifiedShiftedY l h + 1 at horder
  rw [horder]
  abel

end Dixmier.Weyl
