/-
Copyright (c) 2026 Idris Ali Shaik. All rights reserved.
Authors: Idris Ali Shaik
-/
module

public import DixmierFormal.Weyl.RamifiedOperator

public import DixmierFormal.MvPolynomialCompat

@[expose] public section

/-!
# Existence of finite normal-ordered ramified operator expansions

Every element generated by ramified Laurent coefficient multiplication
and the scaled derivative has a finite expression as a linear combination
of `M_f Y^n`. The argument uses the exact coefficient commutator to prove
closure of the span under multiplication. Uniqueness of coefficients is a
separate, still-open PBW theorem.
-/
namespace Dixmier.Weyl

abbrev RamEnd := Module.End ℂ (LaurentPolynomial ℂ)

theorem ramifiedCoeffMul_mul (f g : LaurentPolynomial ℂ) :
    ramifiedCoeffMul f * ramifiedCoeffMul g = ramifiedCoeffMul (f * g) := by
  apply LinearMap.ext
  intro h
  change f * (g * h) = (f * g) * h
  rw [mul_assoc]

/-- The linear span of normal-ordered ramified monomials. -/
noncomputable def normalSpan (l : ℕ) : Submodule ℂ RamEnd :=
  Submodule.span ℂ (Set.range (fun p : LaurentPolynomial ℂ × ℕ =>
    ramifiedCoeffMul p.1 * (ramifiedDerivative l)^p.2))

theorem normalAtom_mem (l : ℕ) (f : LaurentPolynomial ℂ) (n : ℕ) :
    ramifiedCoeffMul f * (ramifiedDerivative l)^n ∈ normalSpan l := by
  apply Submodule.subset_span
  exact ⟨(f,n),rfl⟩

theorem normalSpan_coeff_left (l : ℕ) (f : LaurentPolynomial ℂ)
    (T : RamEnd) (hT : T ∈ normalSpan l) :
    ramifiedCoeffMul f * T ∈ normalSpan l := by
  induction hT using Submodule.span_induction with
  | mem t ht =>
      rcases ht with ⟨⟨g,n⟩,rfl⟩
      rw [← mul_assoc, ramifiedCoeffMul_mul]
      exact normalAtom_mem l (f*g) n
  | zero => simp
  | add x y hx hy ihx ihy =>
      rw [mul_add]
      exact (normalSpan l).add_mem ihx ihy
  | smul c x hx ih =>
      rw [mul_smul_comm]
      exact (normalSpan l).smul_mem c ih

theorem normalSpan_derivative_left (l : ℕ)
    (T : RamEnd) (hT : T ∈ normalSpan l) :
    ramifiedDerivative l * T ∈ normalSpan l := by
  induction hT using Submodule.span_induction with
  | mem t ht =>
      rcases ht with ⟨⟨f,n⟩,rfl⟩
      have hnormal :
          ramifiedDerivative l * (ramifiedCoeffMul f * (ramifiedDerivative l)^n) =
            ramifiedCoeffMul f * (ramifiedDerivative l)^(n+1) +
              ramifiedCoeffMul (ramifiedDerivative l f) *
                (ramifiedDerivative l)^n := by
        calc
        ramifiedDerivative l * (ramifiedCoeffMul f * (ramifiedDerivative l)^n) =
            (ramifiedDerivative l * ramifiedCoeffMul f) *
              (ramifiedDerivative l)^n := by rw [mul_assoc]
        _ = (ramifiedCoeffMul f * ramifiedDerivative l +
              ramifiedCoeffMul (ramifiedDerivative l f)) *
              (ramifiedDerivative l)^n := by rw [ramified_normal_order]
        _ = ramifiedCoeffMul f * (ramifiedDerivative l)^(n+1) +
              ramifiedCoeffMul (ramifiedDerivative l f) *
                (ramifiedDerivative l)^n := by
              simp only [add_mul, mul_assoc, ← pow_succ']
      rw [hnormal]
      exact (normalSpan l).add_mem
        (normalAtom_mem l f (n+1))
        (normalAtom_mem l (ramifiedDerivative l f) n)
  | zero => simp
  | add x y hx hy ihx ihy =>
      rw [mul_add]
      exact (normalSpan l).add_mem ihx ihy
  | smul c x hx ih =>
      rw [mul_smul_comm]
      exact (normalSpan l).smul_mem c ih

theorem normalSpan_derivative_pow_left (l : ℕ) (n : ℕ)
    (T : RamEnd) (hT : T ∈ normalSpan l) :
    (ramifiedDerivative l)^n * T ∈ normalSpan l := by
  induction n with
  | zero => simpa using hT
  | succ n ih =>
      rw [pow_succ']
      rw [mul_assoc]
      exact normalSpan_derivative_left l _ ih

theorem normalSpan_mul (l : ℕ)
    (T U : RamEnd) (hT : T ∈ normalSpan l)
    (hU : U ∈ normalSpan l) : T * U ∈ normalSpan l := by
  induction hT using Submodule.span_induction with
  | mem t ht =>
      rcases ht with ⟨⟨f,n⟩,rfl⟩
      rw [mul_assoc]
      exact normalSpan_coeff_left l f _
        (normalSpan_derivative_pow_left l n U hU)
  | zero => simp
  | add x y hx hy ihx ihy =>
      rw [add_mul]
      exact (normalSpan l).add_mem ihx ihy
  | smul c x hx ih =>
      rw [smul_mul_assoc]
      exact (normalSpan l).smul_mem c ih

theorem ramifiedCoeffMul_one :
    ramifiedCoeffMul (1 : LaurentPolynomial ℂ) = (1 : RamEnd) := by
  apply LinearMap.ext
  intro g
  change (1 : LaurentPolynomial ℂ) * g = g
  simp

theorem ramifiedCoeffMul_C (c : ℂ) :
    ramifiedCoeffMul (LaurentPolynomial.C c) = algebraMap ℂ RamEnd c := by
  apply LinearMap.ext
  intro g
  change LaurentPolynomial.C c * g = c • g
  rw [LaurentPolynomial.smul_eq_C_mul]

theorem ramifiedOperatorAlgebra_normal (l : ℕ) (T : RamEnd)
    (hT : T ∈ ramifiedOperatorAlgebra l) : T ∈ normalSpan l := by
  induction hT using Algebra.adjoin_induction with
  | mem x hx =>
      rcases hx with ⟨f,rfl⟩ | hx
      · simpa using normalAtom_mem l f 0
      · have heq : x = ramifiedDerivative l := Set.mem_singleton_iff.mp hx
        subst x
        simpa [ramifiedCoeffMul_one] using
          normalAtom_mem l (1 : LaurentPolynomial ℂ) 1
  | algebraMap c =>
      rw [← ramifiedCoeffMul_C]
      simpa using normalAtom_mem l (LaurentPolynomial.C c) 0
  | add x y hx hy ihx ihy =>
      exact (normalSpan l).add_mem ihx ihy
  | mul x y hx hy ihx ihy =>
      exact normalSpan_mul l x y ihx ihy

/-- Every generated ramified operator has a finite normal-ordered expression. -/
theorem ramifiedOperatorAlgebra_finite_normal (l : ℕ) (T : RamEnd)
    (hT : T ∈ ramifiedOperatorAlgebra l) :
    ∃ c : (LaurentPolynomial ℂ × ℕ) →₀ ℂ,
      c.sum (fun p a => a • (ramifiedCoeffMul p.1 *
        (ramifiedDerivative l)^p.2)) = T := by
  exact (Finsupp.mem_span_range_iff_exists_finsupp).mp
    (ramifiedOperatorAlgebra_normal l T hT)

/-- Every normal-ordered monomial belongs to the generated algebra,
so its span is contained in that algebra. -/
theorem normalSpan_le_operator (l : ℕ) :
    normalSpan l ≤ (ramifiedOperatorAlgebra l).toSubmodule := by
  apply Submodule.span_le.mpr
  rintro t ⟨⟨f,n⟩,rfl⟩
  exact (ramifiedOperatorAlgebra l).mul_mem
    (coeff_mem_ramifiedOperatorAlgebra l f)
    ((ramifiedOperatorAlgebra l).pow_mem
      (derivative_mem_ramifiedOperatorAlgebra l) n)

/-- The generated ramified algebra is exactly the linear span of
normal-ordered monomials `M_f Y^n`. This states existence, not PBW
coefficient uniqueness. -/
theorem ramifiedOperatorAlgebra_eq_normalSpan (l : ℕ) :
    (ramifiedOperatorAlgebra l).toSubmodule = normalSpan l := by
  apply le_antisymm
  · intro T hT
    exact ramifiedOperatorAlgebra_normal l T hT
  · exact normalSpan_le_operator l

end Dixmier.Weyl
